services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: my_worker
    container_name: email-sender
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info  # Optional: Set Rust log level

