[env]
# Scope down tracing, to filter out external lib tracing.
RUST_LOG="email_backend_worker=debug"

EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT="465"
EMAIL_USER="kazhu.korvi@gmail.com"
EMAIL_PASS="sqkirhhcfvlvmmvz"

WEB_FOLDER="web-folder/"

# Server host and port
SERVER_HOST="127.0.0.1"
SERVER_PORT="4000"
