[env]
# Scope down tracing, to filter out external lib tracing.
RUST_LOG="my_worker=debug"

# Email credentials for FROM compose
EMAIL_FROM="chrislynmarie2000@gmail.com"
EMAIL_FROM_NAME="Ms. C. Dano"

# SMTP credentials
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_USER="dev.castlebyte@gmail.com"
SMTP_PASS="aowxokaxsnbfuxmw"

WEB_FOLDER="web-folder/"

# Server host and port
SERVER_HOST="127.0.0.1"
SERVER_PORT="4000"
